

###################################################################################################
### 手动同步数据源  并发时锁表,待解决
GET {{mapBaseUrl}}/v1/meta/ds/sync?dbIds=100,101,102,103,104,105,106,107
Content-Type: application/json
Authorization: Bearer {{token}}


